pluginManagement {
    repositories {
        mavenLocal()
        maven { name = 'NeoForge'; url = 'https://maven.neoforged.net/releases' }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        maven { name = 'NeoForge'; url = 'https://maven.neoforged.net/releases' }
        mavenCentral()
    }
}

rootProject.name = 'InventoryAdvancementAccelerator'
