allow-flight=true
difficulty=peaceful
enable-command-block=false
enable-query=false
enable-rcon=false
enable-status=false
enforce-secure-profile=false
force-gamemode=false
gamemode=creative
generate-structures=false
level-name=invadvopt-smoke-world
max-players=1
motd=Inventory Advancement Accelerator smoke test
network-compression-threshold=256
online-mode=false
prevent-proxy-connections=false
server-ip=127.0.0.1
server-port=0
simulation-distance=3
spawn-animals=false
spawn-monsters=false
spawn-npcs=false
sync-chunk-writes=true
view-distance=3
white-list=false
